# Generated by Django 5.1.6 on 2025-03-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorEmbedding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vector_id', models.CharField(max_length=255, unique=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.uploadedfile')),
            ],
        ),
    ]
