# Generated by Django 5.1.6 on 2025-04-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_vectorembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorembedding',
            name='vector_id',
            field=models.UUIDField(unique=True),
        ),
    ]
